// Runs after `astro build`. Generates dist/_redirects:
//  - apex (pyzine.com) -> www.pyzine.com   (301)
//  - legacy WordPress permalinks /<slug>.php -> /<slug>  (301, SEO preserved)
import { readdir, writeFile, readFile, access } from 'node:fs/promises';

const ART_DIR = new URL('../src/content/articles/', import.meta.url);
const DIST = new URL('../dist/', import.meta.url);

let slugs = [];
try {
  const files = await readdir(ART_DIR);
  for (const f of files) {
    if (!f.endsWith('.json')) continue;
    const data = JSON.parse(await readFile(new URL(f, ART_DIR)));
    if (data.slug) slugs.push(data.slug);
  }
} catch {
  /* no articles yet */
}
slugs = [...new Set(slugs)].sort();

// NOTE: apex -> www is handled by a Cloudflare Redirect Rule (dashboard), NOT here.
// Cloudflare Pages _redirects sources must be PATHS (starting with /); absolute-URL
// sources are invalid and can cause the whole file to be rejected.
const lines = [
  '# --- Generated by scripts/postbuild.mjs ---',
  '# Legacy WordPress permalinks (.php) -> clean URLs (301, SEO preserved)',
  ...slugs.map((s) => `/${s}.php /${s} 301`),
  '',
];

// preserve any hand-written _redirects that Astro copied from public/
let existing = '';
try {
  await access(new URL('_redirects', DIST));
  existing = await readFile(new URL('_redirects', DIST), 'utf8');
} catch {}
const out = existing && !existing.includes('Generated by scripts/postbuild.mjs')
  ? existing.trimEnd() + '\n\n' + lines.join('\n')
  : lines.join('\n');

await writeFile(new URL('_redirects', DIST), out);
console.log(`postbuild: wrote dist/_redirects with ${slugs.length} legacy .php -> clean redirects`);
