// Runs after `astro build`. Generates dist/_redirects:
//  - apex (pyzine.com) -> www.pyzine.com   (301)
//  - legacy WordPress permalinks /<slug>.php -> /<slug>  (301, SEO preserved)
import { readdir, writeFile, readFile, access } from 'node:fs/promises';

const ART_DIR = new URL('../src/content/articles/', import.meta.url);
const DIST = new URL('../dist/', import.meta.url);

let slugs = [];
try {
  const files = await readdir(ART_DIR);
  for (const f of files) {
    if (!f.endsWith('.json')) continue;
    const data = JSON.parse(await readFile(new URL(f, ART_DIR)));
    if (data.slug) slugs.push(data.slug);
  }
} catch {
  /* no articles yet */
}
slugs = [...new Set(slugs)].sort();

const lines = [
  '# --- Generated by scripts/postbuild.mjs ---',
  '# Canonicalize apex -> www (activate once both domains are attached in Cloudflare Pages)',
  'https://pyzine.com/* https://www.pyzine.com/:splat 301',
  'http://pyzine.com/* https://www.pyzine.com/:splat 301',
  '',
  '# Legacy WordPress permalinks (.php) -> clean URLs',
  ...slugs.map((s) => `/${s}.php /${s} 301`),
  '',
];

// preserve any hand-written _redirects that Astro copied from public/
let existing = '';
try {
  await access(new URL('_redirects', DIST));
  existing = await readFile(new URL('_redirects', DIST), 'utf8');
} catch {}
const out = existing && !existing.includes('Generated by scripts/postbuild.mjs')
  ? existing.trimEnd() + '\n\n' + lines.join('\n')
  : lines.join('\n');

await writeFile(new URL('_redirects', DIST), out);
console.log(`postbuild: wrote dist/_redirects with ${slugs.length} legacy .php redirects + apex->www`);
